
// This file has been generated by the GUI designer. Do not modify.
namespace VotingMultiChain
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label labelTitle;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label IPLabel;
		
		private global::Gtk.Entry ipEntry;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry portEntry;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry rpcUserEntry;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry rpcPasswordentry;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry chainNameEntry;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Button ClientConnect;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VotingMultiChain.MainWindow
			this.Name = "VotingMultiChain.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Multichain voting");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(10));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 550;
			this.DefaultHeight = 550;
			// Container child VotingMultiChain.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelTitle = new global::Gtk.Label ();
			this.labelTitle.Name = "labelTitle";
			this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Connect to blockchain");
			this.vbox2.Add (this.labelTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelTitle]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 5;
			// Container child hbox3.Gtk.Box+BoxChild
			this.IPLabel = new global::Gtk.Label ();
			this.IPLabel.Name = "IPLabel";
			this.IPLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("I.P");
			this.hbox3.Add (this.IPLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.IPLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.ipEntry = new global::Gtk.Entry ();
			this.ipEntry.CanFocus = true;
			this.ipEntry.Name = "ipEntry";
			this.ipEntry.IsEditable = true;
			this.ipEntry.InvisibleChar = '•';
			this.hbox3.Add (this.ipEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ipEntry]));
			w3.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString (" Port");
			this.hbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.portEntry = new global::Gtk.Entry ();
			this.portEntry.CanFocus = true;
			this.portEntry.Name = "portEntry";
			this.portEntry.IsEditable = true;
			this.portEntry.InvisibleChar = '•';
			this.hbox4.Add (this.portEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.portEntry]));
			w5.Position = 1;
			this.hbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox4]));
			w6.Position = 2;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("RPC Username");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.rpcUserEntry = new global::Gtk.Entry ();
			this.rpcUserEntry.CanFocus = true;
			this.rpcUserEntry.Name = "rpcUserEntry";
			this.rpcUserEntry.IsEditable = true;
			this.rpcUserEntry.InvisibleChar = '•';
			this.hbox2.Add (this.rpcUserEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.rpcUserEntry]));
			w9.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("RPC Password ");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.rpcPasswordentry = new global::Gtk.Entry ();
			this.rpcPasswordentry.CanFocus = true;
			this.rpcPasswordentry.Name = "rpcPasswordentry";
			this.rpcPasswordentry.IsEditable = true;
			this.rpcPasswordentry.Visibility = false;
			this.rpcPasswordentry.InvisibleChar = '•';
			this.hbox1.Add (this.rpcPasswordentry);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rpcPasswordentry]));
			w13.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Chain Name      ");
			this.hbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.chainNameEntry = new global::Gtk.Entry ();
			this.chainNameEntry.CanFocus = true;
			this.chainNameEntry.Name = "chainNameEntry";
			this.chainNameEntry.IsEditable = true;
			this.chainNameEntry.InvisibleChar = '•';
			this.hbox5.Add (this.chainNameEntry);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.chainNameEntry]));
			w16.Position = 1;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.ClientConnect = new global::Gtk.Button ();
			this.ClientConnect.CanFocus = true;
			this.ClientConnect.Name = "ClientConnect";
			this.ClientConnect.UseUnderline = true;
			this.ClientConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.hbox6.Add (this.ClientConnect);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.ClientConnect]));
			w18.Position = 0;
			w18.Padding = ((uint)(131));
			this.vbox1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.ClientConnect.Clicked += new global::System.EventHandler (this.OnClientConnectClicked);
		}
	}
}
