
// This file has been generated by the GUI designer. Do not modify.
namespace VotingMultiChain
{
	public partial class VotingWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Label votingTitle;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button candidateOne;

		private global::Gtk.Button candidateTwo;

		private global::Gtk.Button candidateThree;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Button logOutButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget VotingMultiChain.VotingWindow
			this.Name = "VotingMultiChain.VotingWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("VotingWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(10));
			// Container child VotingMultiChain.VotingWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.votingTitle = new global::Gtk.Label();
			this.votingTitle.Name = "votingTitle";
			this.votingTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Voting Station");
			this.vbox4.Add(this.votingTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.votingTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hbox1.Add(this.alignment3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment3]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.vbox1.Add(this.alignment4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment4]));
			w3.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.vbox1.Add(this.alignment5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment5]));
			w4.Position = 2;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w5.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox1.Add(this.alignment2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment2]));
			w6.Position = 2;
			this.alignment1.Add(this.hbox1);
			this.vbox5.Add(this.alignment1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment1]));
			w8.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.candidateOne = new global::Gtk.Button();
			this.candidateOne.WidthRequest = 125;
			this.candidateOne.HeightRequest = 50;
			this.candidateOne.CanFocus = true;
			this.candidateOne.Name = "candidateOne";
			this.candidateOne.UseUnderline = true;
			this.candidateOne.Label = global::Mono.Unix.Catalog.GetString("Vote Candidate 1");
			this.hbox4.Add(this.candidateOne);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.candidateOne]));
			w9.Position = 0;
			w9.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.candidateTwo = new global::Gtk.Button();
			this.candidateTwo.WidthRequest = 125;
			this.candidateTwo.HeightRequest = 50;
			this.candidateTwo.CanFocus = true;
			this.candidateTwo.Name = "candidateTwo";
			this.candidateTwo.UseUnderline = true;
			this.candidateTwo.Label = global::Mono.Unix.Catalog.GetString("Vote Candidate 2");
			this.hbox4.Add(this.candidateTwo);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.candidateTwo]));
			w10.Position = 1;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.candidateThree = new global::Gtk.Button();
			this.candidateThree.WidthRequest = 125;
			this.candidateThree.HeightRequest = 50;
			this.candidateThree.CanFocus = true;
			this.candidateThree.Name = "candidateThree";
			this.candidateThree.UseUnderline = true;
			this.candidateThree.Label = global::Mono.Unix.Catalog.GetString("Vote Candidate 3");
			this.hbox4.Add(this.candidateThree);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.candidateThree]));
			w11.Position = 2;
			w11.Fill = false;
			this.vbox5.Add(this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.vbox5.Add(this.alignment13);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment13]));
			w13.Position = 2;
			this.vbox3.Add(this.vbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox5]));
			w14.Position = 0;
			this.vbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w15.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.logOutButton = new global::Gtk.Button();
			this.logOutButton.CanFocus = true;
			this.logOutButton.Name = "logOutButton";
			this.logOutButton.UseUnderline = true;
			this.logOutButton.Label = global::Mono.Unix.Catalog.GetString("Log Out");
			this.vbox2.Add(this.logOutButton);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.logOutButton]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox4.Add(this.vbox2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox2]));
			w17.Position = 1;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 415;
			this.DefaultHeight = 335;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.candidateOne.Clicked += new global::System.EventHandler(this.OnCandidateOneClicked);
			this.candidateTwo.Clicked += new global::System.EventHandler(this.OnCandidateTwoClicked);
			this.candidateThree.Clicked += new global::System.EventHandler(this.OnCandidateThreeClicked);
			this.logOutButton.Clicked += new global::System.EventHandler(this.OnLogOutButtonClicked);
		}
	}
}
